module.exports = {
  apps: [
    {
      name: 'claudeclaw',
      script: './bridge.js',
      cwd: '/Users/papa/0Proyectos/ClaudeClaw/Opus46',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      env: { NODE_ENV: 'production' },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/Users/papa/.pm2/logs/claudeclaw-error.log',
      out_file:   '/Users/papa/.pm2/logs/claudeclaw-out.log',
      merge_logs: true,
    },
    {
      name: 'code-server',
      script: '/opt/homebrew/opt/code-server/bin/code-server',
      args: '--config /Users/papa/.config/code-server/config.yaml /Users/papa/0Proyectos',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/Users/papa/.pm2/logs/code-server-error.log',
      out_file:   '/Users/papa/.pm2/logs/code-server-out.log',
      merge_logs: true,
    },
    {
      name: 'filebrowser',
      script: '/opt/homebrew/bin/filebrowser',
      args: '--database /Users/papa/.config/filebrowser/filebrowser.db',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/Users/papa/.pm2/logs/filebrowser-error.log',
      out_file:   '/Users/papa/.pm2/logs/filebrowser-out.log',
      merge_logs: true,
    },
    {
      name: 'ttyd',
      script: '/opt/homebrew/bin/ttyd',
      args: '--port 8080 --writable /opt/homebrew/bin/tmux new-session -A -s claudeclaw',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/Users/papa/.pm2/logs/ttyd-error.log',
      out_file:   '/Users/papa/.pm2/logs/ttyd-out.log',
      merge_logs: true,
    },
    {
      name: 'tunnel',
      script: '/opt/homebrew/bin/cloudflared',
      args: 'tunnel --config /Users/papa/.cloudflared/config.yml run',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      restart_delay: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/Users/papa/.pm2/logs/tunnel-error.log',
      out_file:   '/Users/papa/.pm2/logs/tunnel-out.log',
      merge_logs: true,
    },
  ]
};
